# -*- coding: utf-8 -*-
{
    'name': 'Hr Reports',
    'summary': """This module Add Customize Reports For Hr""",
    'description': """This module Add Customize Reports For Hr""",
    'author': 'Business Horizone',
    'category': 'Human Resources',
    'version': '15.0',
    'depends': ['hr_attendance', 'hr_business_trip_ksa', 'hr_employee_eos_ksa', 'hr_leave_ksa', 'hr_letter_request_ksa',
                'hr_loan_ksa', 'hr_vacation_ticket_ksa', 'report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/salary_report.xml',
        'wizard/salary_template.xml',
        'wizard/time_of_report.xml',
        'wizard/time_of_template.xml',
        'wizard/mandate_report.xml',
        'wizard/mandate_template.xml',
        'wizard/loan_report.xml',
        'wizard/loan_template.xml',
        'wizard/employee_details_19.xml',
        'wizard/employee_details_report_template_19.xml',
        'wizard/employee_information.xml',
        'wizard/employee_template.xml',
        'wizard/eos.xml',
        'view/eos_pay.xml',
        'report/report_hr_loan_request.xml',
        'report/reports_registration.xml',

    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
